language: go

sudo: required

services:
  - docker

go:
  - 1.8

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine

before_script:
  - docker version
  - make binary-linux-amd64
  - chmod +x bin/linux/amd64/local-persist
  - sudo ./bin/linux/amd64/local-persist &

script:
  - ./scripts/integration.sh
  - make test

after_success:
  - git checkout dockerhub
  - git merge -ff-only master
  - git push origin dockerhub
